// Code generated by MockGen. DO NOT EDIT.
// Source: internal/order/repository/order_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/order/repository/order_repository.go -destination=internal/order/repository/mocks/mock_order_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
