// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	Status          string             `json:"status"`
	TotalAmount     pgtype.Numeric     `json:"total_amount"`
	ShippingAddress string             `json:"shipping_address"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type OrderItem struct {
	ID        pgtype.UUID        `json:"id"`
	OrderID   pgtype.UUID        `json:"order_id"`
	ProductID pgtype.UUID        `json:"product_id"`
	Quantity  int32              `json:"quantity"`
	UnitPrice pgtype.Numeric     `json:"unit_price"`
	Subtotal  pgtype.Numeric     `json:"subtotal"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Product struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Price       pgtype.Numeric     `json:"price"`
	Stock       int32              `json:"stock"`
	ImageUrl    pgtype.Text        `json:"image_url"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Url struct {
	ID          pgtype.UUID        `json:"id"`
	OriginalUrl string             `json:"original_url"`
	ShortCode   string             `json:"short_code"`
	UserID      pgtype.UUID        `json:"user_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

type User struct {
	ID        pgtype.UUID        `json:"id"`
	Username  string             `json:"username"`
	Password  string             `json:"password"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	Role      string             `json:"role"`
}
