// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateURL(ctx context.Context, arg CreateURLParams) (Url, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteProduct(ctx context.Context, id pgtype.UUID) error
	DeleteURL(ctx context.Context, id pgtype.UUID) error
	GetOrder(ctx context.Context, id pgtype.UUID) (Order, error)
	GetOrderItems(ctx context.Context, orderID pgtype.UUID) ([]OrderItem, error)
	GetOrders(ctx context.Context) ([]Order, error)
	GetProduct(ctx context.Context, id pgtype.UUID) (Product, error)
	GetProducts(ctx context.Context) ([]Product, error)
	GetURLByID(ctx context.Context, id pgtype.UUID) (Url, error)
	GetURLByShortCode(ctx context.Context, shortCode string) (Url, error)
	GetURLsByUserID(ctx context.Context, userID pgtype.UUID) ([]Url, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserOrders(ctx context.Context, userID pgtype.UUID) ([]Order, error)
	UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error)
	UpdateURL(ctx context.Context, arg UpdateURLParams) (Url, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error)
}

var _ Querier = (*Queries)(nil)
