root = "."
tmp_dir = "tmp"

[build]
  cmd = "go build -o ./tmp/main ."
  bin = "tmp/main"
  full_bin = "APP_ENV=development sh -c \"migrate -path ./migrations -database ${DATABASE_URL} up && go run cmd/server/main.go\""
  delay = 1000 # ms
  exclude_dir = ["tmp", "vendor", "testdata", "migrations"]
  exclude_file = []
  exclude_regex = ["_test.go"]
  exclude_unchanged = true
  follow_symlink = true
  log = "build-errors.log"
  include_dir = []
  include_ext = ["go", "tpl", "tmpl", "html"]

[run]
  args = []
  envs = []
  redirect_stderr = false
  
[watch]
  paths = ["."]
  exts = ["go", "tpl", "tmpl", "html", "migrations"]
  
[log]
  time = true
  main_only = false

[color]
  app = ""
  build = "yellow"
  main = "magenta"
  runner = "green"
  watcher = "cyan"

[misc]
  clean_on_exit = false