run:
  timeout: 5m
  tests: true
  skip-dirs:
    - tmp
    - bin
    - vendor
    - testdata
    - mocks
  skip-files:
    - ".*_mock.go$"

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - goconst
    - godot
    - gocyclo
    - revive
    - unconvert
    - unparam
    - nakedret
    - prealloc
    - exportloopref
    - gosec
    - bodyclose
    - noctx
    - nilerr
    - rowserrcheck
    - sqlclosecheck
    - wastedassign

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true

  govet:
    check-shadowing: true

  gocyclo:
    min-complexity: 15

  misspell:
    locale: US

  nakedret:
    max-func-lines: 30

  gosec:
    excludes:
      - G104
      - G204

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - goconst
        - errcheck
