version: "2"

run:
  timeout: 5m
  tests: true

linters:
  # Use standard default linters (errcheck, govet, ineffassign, staticcheck)
  # and add production-ready linters for code quality
  default: standard
  enable:
    # Code Quality & Best Practices
    - unused          # Checks for unused constants, variables, functions and types
    - gocyclo         # Computes and checks the cyclomatic complexity of functions
    - revive          # Fast, configurable, extensible, flexible linter
    - unconvert       # Remove unnecessary type conversions
    - unparam         # Reports unused function parameters
    - nakedret        # Finds naked returns in functions greater than a specified length
    - prealloc        # Finds slice declarations that could potentially be pre-allocated
    - misspell        # Finds commonly misspelled English words in comments
    - goconst         # Finds repeated strings that could be replaced by a constant
    - godot           # Check if comments end in a period

    # Security
    - gosec           # Inspects source code for security problems
    - bodyclose       # Checks whether HTTP response body is closed successfully
    - noctx           # Finds sending http request without context.Context
    - nilerr          # Finds code that returns nil even if it checks that error is not nil
    - rowserrcheck    # Checks whether Err of rows is checked successfully
    - sqlclosecheck   # Checks that sql.Rows and sql.Stmt are closed
    - wastedassign    # Finds wasted assignment statements

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true

    govet:
      enable-all: true

    gocyclo:
      min-complexity: 15

    misspell:
      locale: US

    nakedret:
      max-func-lines: 30

    gosec:
      excludes:
        - G104  # Unhandled errors (covered by errcheck)
        - G204  # Subprocess launched with variable (often needed)

  exclusions:
    # Enable common exclusion presets for cleaner output
    presets:
      - common-false-positives

    # Exclude specific rules for test files
    rules:
      - linters: [gosec, goconst, errcheck]
        path: "_test\\.go$"

    # Exclude specific directories
    paths:
      - tmp
      - bin
      - vendor
      - testdata
      - mocks
      - ".*_mock\\.go$"

formatters:
  enable:
    - goimports  # Format code and manage imports

output:
  formats:
    text:
      path: stdout
  show-stats: true
