x-default-env: &default-env
  TZ: Asia/Bangkok
  LANG: C.UTF-8

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./data:./app/data
    environment:
      GO_ENV: local
