services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - valkey
    environment:
      - DATABASE_HOST=postgres
      - CACHE_HOST=valkey

  postgres:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shortener

  valkey:
    image: valkey/valkey:8-alpine
    ports:
      - "6379:6379"
