x-default-env: &default-env
  TZ: Asia/Bangkok
  LANG: C.UTF-8

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./data:/app/data
    environment:
      <<: *default-env
      GO_ENV: local
