version: '3.8'

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gofiber_boilerplate
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "migrate -path ./migrations -database ${DATABASE_URL} up && air"
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: postgres://root:root@db:5432/gofiber_boilerplate?sslmode=disable
    depends_on:
      - db
    volumes:
      - .:/app
volumes:
  db_data: