services:
  db:
    image: postgres:17
    container_name: booking-db
    environment:
      POSTGRES_DB: bookingdb
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d bookingdb"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: booking-app
    environment:
      PORT: 8080
      DATABASE_URL: postgres://user:password@db:5432/bookingdb?sslmode=disable
      JWT_SECRET: your-secret-key
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data:
