// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql"
)

// Users table for authentication and basic user info
type User struct {
	// UUID v7
	ID string `json:"id"`
	// User email address
	Email string `json:"email"`
	// Bcrypt hashed password
	PasswordHash string `json:"password_hash"`
	// User first name
	FirstName sql.NullString `json:"first_name"`
	// User last name
	LastName sql.NullString `json:"last_name"`
	// Whether the user is active
	IsActive sql.NullBool `json:"is_active"`
	// Creation timestamp
	CreatedAt sql.NullTime `json:"created_at"`
	// Last update timestamp
	UpdatedAt sql.NullTime `json:"updated_at"`
	// Soft delete timestamp
	DeletedAt sql.NullTime `json:"deleted_at"`
}
