apiVersion: apps/v1
kind: Deployment
metadata:
  name: gofiber-app
  labels:
    app: gofiber-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gofiber-app
  template:
    metadata:
      labels:
        app: gofiber-app
    spec:
      containers:
      - name: app
        image: gofiber-skeleton:latest
        ports:
        - containerPort: 3000
          name: http
          protocol: TCP
        - containerPort: 2112
          name: metrics
          protocol: TCP
        env:
        - name: APP_ENV
          value: "production"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: db-host
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: db-password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: db-name
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: redis-host
        - name: REDIS_PORT
          value: "6379"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: jwt-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health/live
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 2
---
apiVersion: v1
kind: Service
metadata:
  name: gofiber-app
  labels:
    app: gofiber-app
spec:
  type: LoadBalancer
  selector:
    app: gofiber-app
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  - port: 2112
    targetPort: 2112
    protocol: TCP
    name: metrics
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  redis-host: "redis-service"
  log-level: "info"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: gofiber-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: gofiber-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
