# Application Configuration
server:
  port: 8080

database:
  host: "localhost"
  port: 5432
  user: "user"
  password: "password"
  dbname: "shortener"
  sslmode: "disable"

jwt:
  secret: "your-secret-key"
  expiration: 72 # in hours

cache:
  host: "localhost"
  port: 6379
  password: ""
  db: 0
