app:
  port: 8080
  env: development

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: gofiber_skeleton
  ssl_mode: disable

jwt:
  secret: your_jwt_secret_here_change_in_production
  expires_in: 24h

log:
  level: info