app:
  port: 8080
  env: development

database:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  name: gofiber_skeleton
  ssl_mode: disable

jwt:
  secret: "your-very-secret-key"
  expiration_in: 1h

log:
  level: info