# Application Configuration
# This file contains the primary configuration settings for the URL shortener application.
# It is structured to be easily readable and maintainable, following YAML best practices.

server:
  # Host address where the server will listen. For local development, "localhost" is typical.
  host: "localhost"
  # Port number on which the server will listen for incoming HTTP requests.
  port: 8080
  # The domain name for the application, used for generating full short URLs.
  # Example: "http://localhost:8080" or "https://your-app.com"
  app_domain: "http://localhost:8080"

cache:
  # Host address for the caching service (e.g., Redis).
  host: "localhost"
  # Port number for the caching service.
  port: 6379
  # Password for the caching service. Leave empty if no password is set.
  password: ""
  # Database number to use in the caching service (e.g., Redis DB 0).
  db: 0