// Code generated by MockGen. DO NOT EDIT.
// Source: user.go
//
// Generated by this command:
//
//	mockgen -source=user.go -destination=../../test/mocks/mock_user_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
