// Code generated by MockGen. DO NOT EDIT.
// Source: internal/product/repository/product_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/product/repository/product_repository.go -destination=internal/product/repository/mocks/mock_product_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks
