// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreatePost(ctx context.Context, arg CreatePostParams) (Posts, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (Users, error)
	DeactivateUser(ctx context.Context, id pgtype.UUID) error
	DeletePost(ctx context.Context, id pgtype.UUID) error
	GetPostByID(ctx context.Context, id pgtype.UUID) (GetPostByIDRow, error)
	GetPostBySlug(ctx context.Context, slug string) (GetPostBySlugRow, error)
	GetUserByEmail(ctx context.Context, email string) (Users, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (Users, error)
	ListPosts(ctx context.Context, arg ListPostsParams) ([]ListPostsRow, error)
	ListPostsByUser(ctx context.Context, arg ListPostsByUserParams) ([]Posts, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]Users, error)
	PublishPost(ctx context.Context, id pgtype.UUID) (Posts, error)
	UnpublishPost(ctx context.Context, id pgtype.UUID) (Posts, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Posts, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (Users, error)
	UpdateUserLastLogin(ctx context.Context, id pgtype.UUID) error
}

var _ Querier = (*Queries)(nil)
