// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package testdb

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Url struct {
	ID          uuid.UUID
	OriginalUrl string
	ShortCode   string
	UserID      uuid.NullUUID
	CreatedAt   time.Time
	ExpiresAt   sql.NullTime
}

type User struct {
	ID        uuid.UUID
	Username  string
	Password  string
	CreatedAt time.Time
	UpdatedAt time.Time
}
