// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package entity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CountPostsByStatus(ctx context.Context) (CountPostsByStatusRow, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	DeletePost(ctx context.Context, id pgtype.UUID) error
	GetAllPosts(ctx context.Context, arg GetAllPostsParams) ([]GetAllPostsRow, error)
	GetDraftPostsByUserID(ctx context.Context, userID pgtype.UUID) ([]Post, error)
	GetPostByID(ctx context.Context, id pgtype.UUID) (Post, error)
	GetPostsByUserID(ctx context.Context, userID pgtype.UUID) ([]Post, error)
	GetPostsWithAuthor(ctx context.Context, arg GetPostsWithAuthorParams) ([]GetPostsWithAuthorRow, error)
	GetPublishedPostsByUserID(ctx context.Context, userID pgtype.UUID) ([]Post, error)
	GetUserPostStats(ctx context.Context, userID pgtype.UUID) (GetUserPostStatsRow, error)
	SearchPosts(ctx context.Context, arg SearchPostsParams) ([]SearchPostsRow, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (Post, error)
}

var _ Querier = (*Queries)(nil)
