basePath: /api/v1
host: localhost:8080
info:
  contact:
    email: system-admin@zercle.tech
    name: API Support
    url: https://zercle.tech
  description: This is a sample API for an e-commerce application.
  license:
    name: MIT
    url: https://mit-license.org/
  title: E-commerce API
  version: "1.0"
paths: {}
schemes:
- http
swagger: "2.0"
