package app

import (
	"log"

	swagger "github.com/arsmn/fiber-swagger/v2"
	"github.com/gofiber/fiber/v2"
	"github.com/gofiber/fiber/v2/middleware/cors"
	"github.com/gofiber/fiber/v2/middleware/logger"

	_ "gofiber-skeleton/docs" // docs is generated by Swag CLI, you have to import it.
	"gofiber-skeleton/pkg/config"
	"gofiber-skeleton/pkg/database"
)

// @title Go Fiber Monorepo API
// @version 1.0
// @description This is a sample Go Fiber Monorepo API.
// @termsOfService http://swagger.io/terms/

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2000.html

// @host localhost:8080
// @BasePath /

func SetupApp(migrationsPath string) *fiber.App {
	cfg, err := config.LoadConfig()
	if err != nil {
		log.Fatalf("Error loading config: %v", err)
	}

	database.ConnectDB(cfg.DATABASE_URL)
	database.RunMigrations(migrationsPath, cfg.DATABASE_URL)

	app := fiber.New()

	// Middleware
	app.Use(cors.New())
	app.Use(logger.New())

	// Swagger UI
	app.Get("/swagger/*", swagger.New())


	app.Get("/", func(c *fiber.Ctx) error {
		return c.SendString("Hello, Fiber Monorepo!")
	})

	return app
}
