// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreatePost(ctx context.Context, arg CreatePostParams) (CreatePostRow, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeletePost(ctx context.Context, id uuid.UUID) error
	GetPostByID(ctx context.Context, id uuid.UUID) (GetPostByIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListPostsByThread(ctx context.Context, threadID uuid.UUID) ([]ListPostsByThreadRow, error)
	ListPostsByUser(ctx context.Context, userID uuid.UUID) ([]ListPostsByUserRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdatePost(ctx context.Context, arg UpdatePostParams) (UpdatePostRow, error)
}

var _ Querier = (*Queries)(nil)
