name: Deploy to Production

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.25'

    - name: Run tests before deploy
      run: |
        go test -v -race ./test/unit/...
        go test -v -race ./test/integration/...

    - name: Run linter
      run: |
        go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
        golangci-lint run ./... --timeout=10m

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract version from tag
      id: tag
      run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.version }}
          ghcr.io/${{ github.repository }}:latest
        labels: |
          org.opencontainers.image.version=${{ steps.tag.outputs.version }}
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        body: |
          ## Docker Image
          ```
          ghcr.io/${{ github.repository }}:${{ steps.tag.outputs.version }}
          ```

          ## Changes
          See commits between previous release and this one for details.
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
