name: Go CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}


permissions:
  contents: read

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions:setup-go@v5
      with:
        go-version: 'stable'

    - name: Go Mod Download
      run: go mod download

    - name: Install mockgen
      run: go install github.com/golang/mock/mockgen@latest

    - name: Go Generate
      run: go generate ./...

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v8
      with:
          version: latest

    - name: Run Tests
      run: go test -v -race ./...