name: go

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  # Required: allow read access to the content for analysis.
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  pull-requests: read
  # Optional: allow write access to checks to allow the action to annotate code in the PR.
  checks: write

jobs:

  build:
    strategy:
      matrix:
        go-version: [stable, oldstable ]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    env:
      CGO_ENABLED: 0
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Test
      run: go test -v -cover ./...

    - name: Build
      run: go build -v -ldflags "-s -w" -trimpath ./...
